suites:
  - name: docker-default
    attributes:
      docker:
        version: 1.10.0
    run_list:
      - recipe[apt]
      - recipe[apt-docker]
      - recipe[docker_test::installation_package]
      - recipe[docker_test::service_upstart]
      - recipe[docker_test::auto]
    includes: [ubuntu-14.04]
